spring:
  application:
    name: api-gateway
server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: true

