spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/ecommerce-platform
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/