spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8090/realms/ecommerce-platform
eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/