spring:
  application:
    name: stock-service
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090/realms/ecommerce-platform
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
