spring:
  application:
    name: stock-service
  datasource:
    url: jdbc:postgresql://localhost:5432/stock_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: stock
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer : org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    topic:
      name: order_topics

server:
  port: 8082
