  name: JAVA CI
  on:
    push:
      branches:
        - '**'
    pull_request:
      branches:
        - main
  jobs:
    build-stock-service:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Set up JDK 21
          uses: actions/setup-java@v4
          with:
            distribution: temurin
            java-version: '21'
            cache: maven
        - name: Build Base Domains
          working-directory: base-domains
          run: mvn clean install
        - name: Build stock service
          working-directory: stock-service
          run: mvn clean package -DskipTests

