name: JAVA CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-services:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      # ---------------- EUREKA SERVER ----------------

      - name: Build Eureka Server
        working-directory: discovery-server
        run: mvn clean package -DskipTests

      # ---------------- API-GATEWAY ----------------

      - name: Build API Gateway
        working-directory: api-gateway
        run: mvn clean package -DskipTests


      # ---------------- BASE DOMAINS ----------------

      - name: Build Base Domains
        working-directory: base-domains
        run: mvn clean install -DskipTests

      # ---------------- PRODUCT SERVICE ----------------

      - name: Build Product Service
        working-directory: product-service
        run: mvn clean package -DskipTests

      # ---------------- STOCK SERVICE ----------------

      - name: Build Stock Service
        working-directory: stock-service
        run: mvn clean package -DskipTests

      # ---------------- ORDER SERVICE ----------------

      - name: Build Order Service
        working-directory: order-service
        run: mvn clean package -DskipTests


      # ---------------- EMAIL SERVICE ----------------

      - name: Build Email Service
        working-directory: email-service
        run: mvn clean package -DskipTests





